services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-pzn
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: contact_management_api
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
